_target_: models.explicit.ExplicitModel
tag: explicit
enc_cfg:
  _target_: models.gpt.GPT
  tag: medium_gpt
  block_size: 300
  vocab_size : 512
  n_layer: 4
  n_head: 8
  n_embd: 512
  dropout: 0.0
  bias: True
  positional_encodings: True
pred_cfg:
  _target_: models.explicit.MLP
  in_dim : 1024
  dim : 2048
  out_dim: ${eval:'${...data.n_obs} + 1'}
  n_hidden_layers: 3
markov_pred: True