batch_size: 512
pretrained_id: 3gx9owf7
lr: 0.0001
n_embd: 384
n_layers: 3
n_heads: 6
val_split: 0.1
seq_conditional_dim: 384
cond_encoder_kwargs: 
  n_layers: 2
  n_heads: 4
  vocab_size: null

dataset:
  context_length: [1, 50]
  pretrained_embedding: True
  pretrained_embedding_id: 3gx9owf7
  known_n_embd: 384
  sequential: False