_target_: task.ReftConfig
low_rank_dimension: 16
layers: [3]
t_slice: [-1,null,-1]
component: output
reft_cls: loreft


#tune/method_config: reft_base
#tune.method_config.low_rank_dimension: 16
#tune.method_config.layers: "[1,2,3,4,5], [1,3,5], [3]"
#tune.method_config.t_slice: [-1,null,-1]
#tune.method_config.component: mixer.output
#tune.method_config.reft_cls: loreft, direft, noreft, consreft