tag: gpt100M
decoder:
  _target_: models.decoder.TransformerDecoder
  max_seq_len: 300
  num_tokens : ${eval:'${task.metalearn.data.n_obs} + 1'}
  n_layer: 10
  n_head: 8
  n_embd: 1024
  causal_mask: False
  full_context: False
  positional_encodings: True