tag: gpt5M
decoder:
  _target_: models.decoder.TransformerDecoder
  max_seq_len: 300
  num_tokens : ${eval:'${task.metalearn.data.n_obs} + 1'}
  n_layer: 6
  n_head: 8
  n_embd: 256
  causal_mask: True
  full_context: True
  positional_encodings: True