sweep_id: gru_size${now:%Y-%m-%d}-${now:%H-%M-%S}

task/metalearn: base

task/metalearn/data: small
task/metalearn/model: gru10M
task.metalearn.data.context_length: [200,200]
task.metalearn.model.decoder.n_layer: 2,4,6
seed: 15

model_checkpoint: base
max_steps: 10000 # won't reach the max, max_tokens is our stopping condition