sweep_id: base_known_small_2${now:%Y-%m-%d}-${now:%H-%M-%S}

task/metalearn: base

task/metalearn/data: small
task/metalearn/model: ctx/known_small_soft_3, ctx/known_small_soft_4, ctx/known_small_soft_5
seed: 15

model_checkpoint: base
max_steps: 50000 # won't reach the max, max_tokens is our stopping condition