n_embd: 256
n_layers: 4
n_heads: 6
dropout: 0.0
scale_shift: True
seq_conditional: True
seq_unconditional_prob: 0.0
cond_modulation: True
self_condition: False
seq_conditional_dim: 384
cond_encoder_kwargs:
  n_layers: 8
  n_heads: 8
  vocab_size: 50