data : 
  n_states: 20
  n_obs: 50
  context_length: [10,200]
  context_length_dist: uniform
  seed: 42
  base_cycles: 4
  base_directions: 2
  base_speeds: 2
  cycle_families: 3
  group_per_family: 2
  cycle_per_group: 3
  family_directions: 2
  family_speeds: 2
  emission_groups: 3
  emission_group_size: 2
  emission_shifts: 3
  emission_edge_per_node: 3

model:
  block_size: 300
  vocab_size: ${..data.n_obs} 
  n_layer: 6
  n_head: 6
  n_embd: 216
  dropout: 0.0
  bias: True

val_size: 1000
batch_size: 512
lr: 1e-3