data : 
    n_states: 30
    n_obs: 60
    context_length: [10,200]
    context_length_dist: exponential
    seed: 42
    base_cycles: 4
    base_directions: 2
    base_speeds: 3
    cycle_families: 4
    group_per_family: 2
    cycle_per_group: 3
    family_directions: 2
    family_speeds: 2
    emission_groups: 4
    emission_group_size: 2
    emission_shifts: 3
    emission_edge_per_node: 3

model:
  block_size: 200
  vocab_size: 60 
  n_layer: 8
  n_head: 8
  n_embd: 512
  dropout: 0.0
  bias: True

val_size: 1000
batch_size: 512
lr: 1e-3