sweep_id: explicit_mlp1${now:%Y-%m-%d}-${now:%H-%M-%S}

task/data: small
task/model: explicit_mlp
task.data.context_length: [100,100]
task.data.block_diag_mask: False
seed: 12,17
model_checkpoint.save_top_k: -1

max_steps: 10000000000000000 # won't reach the max, seen_tokens is our stopping condition
max_tokens: 1000000000 # 1B