sweep_id: known_unconditional_${now:%Y-%m-%d}-${now:%H-%M-%S}

task: known_unconditional

task.loss: l2
task.diffusion.normalize_latent: True, False
task.diffusion.objective: pred_v
task.diffusion.latent_shape: '[1,384], [1,512]'

val_check_interval: 250
model_checkpoint: base
model_checkpoint.every_n_train_steps: 500

seed: 15

max_steps: 1000000 # won't reach the max, time will stopping criterion