sweep_id: lora_midseq_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: duy6u49u, ale6kz0k
tune.constraints:  "[[1, 0]], [[2,0]], [[6,0]], [[7,0]]"
tune.batch_size: 32
tune.precompute_pp: True
tune.prefix_size: [50,70]

tune/method_config: lora_base
tune.method_config.r: 4
tune.method_config._target_: peft.LoraConfig
tune.method_config.target_modules: all-linear
