sweep_id: lora_cons_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: duy6u49u, ale6kz0k
tune.batch_size: 32
tune.constraints: [[1,0],[2,0],[4,1],[6,0],[7,0]]
tune.context_length: [50,50]
tune.precompute_pp: true

tune/method_config: lora_base
tune.method_config.r: 6
tune.method_config._target_: peft.LoraConfig
tune.method_config.target_modules: all-linear