sweep_id: occams_ssm${now:%Y-%m-%d}-${now:%H-%M-%S}

task/data: small
task/model: mamba10M
task.data.context_length: "[200,200], [1,200]"
task.data.adjust_varlen_batch: True, False
seed: 15
model_checkpoint: base

max_steps: 10000 # won't reach the max, seen_tokens is our stopping condition
max_tokens: 10000000000000 # 1B