sweep_id: reft_mamba_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: ale6kz0k
tune.batch_size: 32
tune.constraints: [[1, 0]]
tune/method_config: reft_base

tune.method_config._target_: task.ReftConfig
tune.method_config.low_rank_dimension: 32
tune.method_config.layers: "[3], [2,3,4,5]"
tune.method_config.t_slice: "[-1, -2, -1], [-1,null,-1]"
tune.method_config.component: output, mixer.output