sweep_id: reft_cls_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: duy6u49u
tune.batch_size: 32
tune.constraints: [[1, 0]]
tune/method_config: reft_base

tune.method_config._target_: task.ReftConfig
tune.method_config.low_rank_dimension: 32
tune.method_config.layers: "[3]"
tune.method_config.t_slice: "[-1, -2, -1], [-1,null,-1]"
tune.method_config.component: output
tune.method_config.reft_cls: loreft, direft, noreft, consreft