sweep_id: reft_midseq_mamba_med_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: ale6kz0k
tune.constraints:  [[1, 0], [2, 0], [6, 0], [7, 0]]
tune.batch_size: 32
tune.precompute_pp: True
tune.prefix_size: [30,70]

tune/method_config: reft_base
tune.method_config.low_rank_dimension: 8
tune.method_config.layers: "[1,2,3,4,5]"
tune.method_config.t_slice: "[-1,null,-1]"
tune.method_config.component: mixer.output
