sweep_id: reft_1_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: ale6kz0k, duy6u49u 
tune.batch_size: 32
tune.constraints: "[[1, 0],[7, 0]], [[1, 0]]"
tune/method_config: reft_base

tune.method_config._target_: task.ReftConfig
tune.method_config.low_rank_dimension: 4,16
tune.method_config.layers: "[3], [2,4]"
tune.method_config.t_slice: "[-1, -2, -1], [-1,null,-1]"
tune.method_config.component: output