sweep_id: reft_${now:%Y-%m-%d}-${now:%H-%M-%S}

tune.pretrained_id: 9qs3bntc, e72ebe43
tune.batch_size: 32
tune.constraints: "[[1, 0]], [[2, 0]]"

tune.method_config._target_: task.ReftConfig
tune.method_config.low_rank_dimension: 2,4 
tune.method_config.layers: "[3], [5]"
tune.method_config.t_slice: "[-1, -2, -1], [-1,null,-1], [-1, null, -2]"
tune.method_config.component: output