sweep_id: xd1_${now:%Y-%m-%d}-${now:%H-%M-%S}

task: known_transformer_encoder_small, known_transformer_encoder_big

task.diffusion.normalize_latent: False
task.diffusion.objective: pred_v
task.diffusion.self_condition: False
task.dataset.context_length: [1,30]
task.lr_scheduler: False

val_check_interval: 250
model_checkpoint: base
model_checkpoint.every_n_train_steps: 500

seed: 15

max_steps: 100000 # won't reach the max, time will stopping criterion