defaults:
  - train_config
  - _self_
  - task: known_transformer
  - model_checkpoint: null
  - hydra/sweeper/params : null
  - override hydra/launcher: base_slurm

val_check_interval: 50
accelerator: ???
seed: 42
log_dir: ${oc.env:SCRATCH}/diffusion_train_log
max_steps: 100000

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/hydra_multiruns/${sweep_id}
    subdir: ${hydra.job.num}

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: null
  project: "diffusion_train"
  save_dir: ${log_dir}
  offline: False
  tags: null  