batch_size: 512
val_split: 0.1
pretrained_id: turo071i # gru10M
lr: 0.0001

model:
  n_embd: 256
  n_layers: 4
  n_heads: 6
  dropout: 0.0
  scale_shift: True
  seq_conditional: True
  cond_encoder_kwargs:
    n_layers: 2
    n_heads: 4
    vocab_size: null
  
dataset:
  _target_: data.diffusion.GRUDiffusionDatasetConfig
  context_length: [200, 200]
  suffix_size: [1,30]
  pretrained_embedding: True
  pretrained_embedding_id: turo071i