batch_size: 512
val_split: 0.1
pretrained_id: og8dp02h # gru5M_mlp
lr: 0.0001
loss: l2
train_schedule: cosine
diffusion_objective: pred_v
tag: grumlp_ids

model:
  n_embd: 256
  n_layers: 4
  n_heads: 6
  dropout: 0.0
  scale_shift: True
  seq_conditional: True
  seq_unconditional_prob: 0.0
  cond_modulation: True
  self_condition: False
  seq_conditional_dim: 384
  cond_encoder_kwargs:
    n_layers: 8
    n_heads: 8
    vocab_size: 50
  
dataset:
  _target_: data.diffusion.GRUDiffusionDatasetConfig
  context_length: [200, 200]
  suffix_size: [1,30]
  pretrained_embedding: False
  cond_hidden: False