batch_size: 512
val_split: 0.1
pretrained_id: 1elo1tjg
lr: 0.0001
loss: l2
train_schedule: cosine
diffusion_objective: pred_v

model:
  n_embd: 512
  n_layers: 8
  n_heads: 8
  dropout: 0.0
  scale_shift: True
  seq_conditional: True
  cond_modulation: True
  seq_conditional_dim: 512
  cond_encoder_kwargs:
    n_layers: 8
    n_heads: 8
    vocab_size: 50
    
dataset:
  _target_: data.diffusion.KnownEncoderDiffusionDatasetConfig
  context_length: [1, 30]
  pretrained_embedding: False
  pretrained_encoder_id: 1elo1tjg