batch_size: 512
val_split: 0.1
pretrained_id: 1elo1tjg
lr: 0.0001
loss: l2
train_schedule: cosine
diffusion_objective: pred_v

model:
  n_embd: 384
  n_layers: 6
  n_heads: 8
  dropout: 0.0
  scale_shift: True
  seq_conditional: True
  cond_modulation: True
  cond_encoder_kwargs:
    n_layers: 2
    n_heads: 8
    vocab_size: null
    
dataset:
  _target_: data.diffusion.KnownEncoderDiffusionDatasetConfig
  context_length: [1, 30]
  pretrained_embedding: True
  pretrained_embedding_id: f818u4jn
  pretrained_encoder_id: 1elo1tjg