defaults:
  - experiment_config
  - task: base
  - _self_

check_val_every_n_epoch: 1
accelerator: gpu
seed: 42
log_dir: ${oc.env:SCRATCH}/latent_control_log
epochs: 100
offline: False

hydra:
  run:
    dir: ${log_dir}/outputs/${now:%Y-%m-%d}_${now:%H-%M-%S}