defaults:
  - train_config
  - _self_
  - task: null
  - tune: base
  - hydra/sweeper/params : null
  - override hydra/launcher: base_slurm

val_check_interval: 50
accelerator: ???
seed: 42
log_dir: ${oc.env:SCRATCH}/latent_control_log
max_steps: 10000
sweep_id: ${now:%Y-%m-%d}_${now:%H-%M-%S}

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/hydra_multiruns/${sweep_id}
    subdir: ${hydra.job.num}

model_checkpoint: 
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ??? # To be set using the Wandb run id
  filename: "{epoch:03d},{step:03d}"
  auto_insert_metric_name: True
  monitor: val/ce_loss
  mode: min
  save_top_k: 1
  save_last: link
  every_n_train_steps: 250

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: null
  project: "latent_control"
  save_dir: ${log_dir}
  offline: True
  tags: null  