defaults:
  - submitit_slurm

mem_gb: 32
gres: gpu:1
tasks_per_node: 1
array_parallelism: 32
cpus_per_task: 1
timeout_min: 2000 # ~3 days
partition: long-grace
additional_parameters:
  no-requeue: true

setup:
  - "source ~/latent_control/venv/bin/activate"