pretrained_id: xe5rzc42
batch_size: 256
traj_len: 20
traj_per_epoch: 4096
traj_repeat: 2
seed: 42
reward_type: target
clip_coef: 0.2
clip_vloss: False
vf_coef: 0.5
ent_coef: 0.01
pred_coef: 0.2
normalize_advantages: False
normalize_rewards: True
gae_lambda: 0.95
discount_factor: 0.0
rollout_batch_size: 1024
lr: 0.0001
noop_prob: 0.75