_target_: models.explicit.ExplicitModel
tag: explicit
pred_cfg:
  _target_: models.gpt.GPT
  tag: medium_gpt
  block_size: 300
  vocab_size : ${eval:'${...data.n_obs} + 1'}
  n_layer: 6
  n_head: 8
  n_embd: 512
  dropout: 0.0
  bias: True
  positional_encodings: True
enc_cfg:
  _target_: models.explicit.KnownEncoder
  n_embd: 512
  latents_shape: null