_target_: models.explicit.ExplicitModel
tag: explicit_known_mlp
pred_cfg:
  _target_: models.explicit.MLP
  in_dim : 1024
  dim : 2048
  out_dim: ${eval:'${...data.n_obs} + 1'}
  n_hidden_layers: 3
enc_cfg:
  _target_: models.explicit.KnownEncoder
  n_embd: 512
  latents_shape: null
markov_pred: True
vocab_size: 300
