sweep_id: dsm-context${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: base
task/dsm/dataset: context
task.dsm.pretrained_id: wy6dmb37, 8dv6dg67, t6r7dvg7, vyocaiqr, cn17llwj, 7xwvtiem, fybu97wi # known, gpt_bn, gru_bn, gpt-pooled, gru-pooled, gpt[ctx]-pooled, gru[ctx]-pooled
model_checkpoint: base

seed: 15

max_steps: 100000