sweep_id: dsm-context${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: base
task/dsm/dataset: context
task.dsm.dataset.pretrained_id: vyocaiqr, cn17llwj # gpt-pooled, gru-pooled
model_checkpoint: base

seed: 15

max_steps: 100000