sweep_id: dsm-hidden_new${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: base
task/dsm/dataset: hidden
task.dsm.dataset.pretrained_id: 6enbwdmh # gru
task.dsm.dataset.diffuse_logits: False
model_checkpoint: base
task/dsm/model: cond_input_ids
task.dsm.dataset.context_length: '[190, 190], [200, 200]'

seed: 15

max_steps: 200000