sweep_id: dsm-long-context-test${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: base
task/dsm/dataset: context
task/dsm/model: cond_input_ids_large
task.dsm.dataset.pretrained_id: gtpgvujm
task.dsm.dataset.context_length: [1, 100]
model_checkpoint: base

seed: 15

max_steps: 200000

