sweep_id: dsm-size_${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: known_large
task.dsm.diffusion_objective: pred_noise, pred_v
task.dsm.loss: l2
task.dsm.lr: 0.00005

model_checkpoint: base

seed: 15

max_steps: 1000000