sweep_id: dsm-size_${now:%Y-%m-%d}-${now:%H-%M-%S}

task/dsm: known_large
task.dsm.diffusion_objective: pred_noise, pred_v
task.dsm.loss: l2
model_checkpoint: base
task.dsm.model.seq_unconditional_prob: 0.2

seed: 15

max_steps: 1000000