batch_size: 10
pretrained_id: 1elo1tjg
lr: 0.0001
max_steps: ${max_steps}
exploratory: True
train_direction: fwd

model:
  latent_shape: null
  n_embd: 128
  n_layers: 3
  n_heads: 4
  dropout: 0.0
  scale_shift: True
  seq_conditional: True
  langevin: False
  lgv_clip: 1e2
  gfn_clip: 1e4
  learned_variance: True
  cond_encoder_kwargs:
    n_layers: 2
    n_heads: 4
    vocab_size: null

dataset:
  _target_: data.diffusion.KnownEncoderDiffusionDatasetConfig
  context_length: [1, 30]
  pretrained_embedding: True
  pretrained_embedding_id: f818u4jn
  pretrained_encoder_id: 1elo1tjg