tag: gpt_1
encoder:
  _target_: models.encoder.TransformerEncoder
  max_seq_len: 300
  num_tokens : ${task.metalearn.data.n_obs}
  n_layer: 3
  n_head: 6
  n_embd: 64
  causal_mask: True
  sin_posemb: True
  bottleneck: False